### ISSUE TITLE
plugin "bridg" not found

### ISSUE THREAD

**Issue by mrSingh007** [felipewind/poc-mosquitto-quarkus-angular#1]
when I did docker compose up, everything works fine till network step. It gave the error 
```
 ⠿ Network mosquitto_poc-mqtt-net  Error                                                                                    15.0s
failed to create network mosquitto_poc-mqtt-net: Error response from daemon: plugin "bridg" not found
```

whole log:
```
user@macOs  docker compose up
[+] Running 21/21
 ⠿ angular Pulled                                                                                                           27.5s
   ⠿ 69692152171a Pull complete                                                                                             18.4s
   ⠿ 30afc0b18f67 Pull complete                                                                                             24.8s
   ⠿ 596b1d696923 Pull complete                                                                                             24.9s
   ⠿ febe5bd23e98 Pull complete                                                                                             24.9s
   ⠿ 8283eee92e2f Pull complete                                                                                             24.9s
   ⠿ 351ad75a6cfa Pull complete                                                                                             25.0s
   ⠿ cc0c47cc3f53 Pull complete                                                                                             25.1s
 ⠿ mosquitto Pulled                                                                                                         30.9s
   ⠿ 339de151aab4 Pull complete                                                                                             28.1s
   ⠿ 8cc7b833e2db Pull complete                                                                                             28.2s
   ⠿ f2b454175e7e Pull complete                                                                                             28.3s
   ⠿ 5212eec4186b Pull complete                                                                                             28.5s
 ⠿ quarkus Pulled                                                                                                           44.0s
   ⠿ 8f403cb21126 Pull complete                                                                                             21.7s
   ⠿ 65c0f2178ac8 Pull complete                                                                                             21.7s
   ⠿ 2168ef47c1a3 Pull complete                                                                                             41.2s
   ⠿ 91e2b4503f8c Pull complete                                                                                             41.5s
   ⠿ 467a4c3e4a32 Pull complete                                                                                             41.5s
   ⠿ 6f360d945d22 Pull complete                                                                                             41.5s
   ⠿ 7e1208afb9ee Pull complete                                                                                             41.6s
[+] Running 0/1
 ⠿ Network mosquitto_poc-mqtt-net  Error                                                                                    15.0s
failed to create network mosquitto_poc-mqtt-net: Error response from daemon: plugin "bridg" not found

```

**Comment by felipewind** [comment]
Hello @mrSingh007 !

Is it possible that you erased the last `e` from `bridge`? I mean, you made a typo and changed from `bridge` to `bridg` ?

I just executed `docker-compose up` in this docker-compose.yaml (the same which is in the README.md) and everything worker fined:

```yaml
version: "3.8"

services:

  mosquitto:
    container_name: mqtt-mosquitto
    image: felipewind/poc-mqtt-mosquitto:2.0.10
    build:
      context: ./mosquitto/
      dockerfile: ./Dockerfile
    restart: always
    networks:
      - poc-mqtt-net
    ports:
      - 1883:1883
      - 9001:9001

  quarkus:
    container_name: mqtt-quarkus
    image: felipewind/poc-mqtt-quarkus:1.0
    build:
      context: ./quarkus/
      dockerfile: ./src/main/docker/Dockerfile.jvm
    ports:
      - 8080:8080
    networks:
      - poc-mqtt-net
    depends_on:
      - mosquitto
    environment:
      - mp.messaging.outgoing.topic-send-chat.host=mosquitto
      - mp.messaging.incoming.topic-receive-chat.host=mosquitto

  angular:
    container_name: mqtt-angular
    image: felipewind/poc-mqtt-angular:1.0
    build:
      context: ./angular/
      dockerfile: ./Dockerfile
    ports:
      - 80:80
    networks:
      - poc-mqtt-net
    depends_on:      
      - mosquitto


networks:
  poc-mqtt-net:
    driver: bridge
```

Here is my Docker and Docker Compose versions:

```bash
$ docker --version
Docker version 19.03.12, build 48a66213fe

$ docker-compose --version
docker-compose version 1.25.5, build 8a1c60f6
```
